// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: survey.proto

package fr.eip.aura.udp.proto;

public final class SurveyProto {
  private SurveyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SurveyQuestionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SurveyQuestion)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string question = 2;</code>
     */
    java.lang.String getQuestion();
    /**
     * <code>string question = 2;</code>
     */
    com.google.protobuf.ByteString
        getQuestionBytes();

    /**
     * <code>string answer = 3;</code>
     */
    java.lang.String getAnswer();
    /**
     * <code>string answer = 3;</code>
     */
    com.google.protobuf.ByteString
        getAnswerBytes();
  }
  /**
   * Protobuf type {@code SurveyQuestion}
   */
  public  static final class SurveyQuestion extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SurveyQuestion)
      SurveyQuestionOrBuilder {
    // Use SurveyQuestion.newBuilder() to construct.
    private SurveyQuestion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SurveyQuestion() {
      id_ = 0;
      question_ = "";
      answer_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SurveyQuestion(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              question_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              answer_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.eip.aura.udp.proto.SurveyProto.internal_static_SurveyQuestion_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.eip.aura.udp.proto.SurveyProto.internal_static_SurveyQuestion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.class, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int QUESTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object question_;
    /**
     * <code>string question = 2;</code>
     */
    public java.lang.String getQuestion() {
      java.lang.Object ref = question_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        question_ = s;
        return s;
      }
    }
    /**
     * <code>string question = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWER_FIELD_NUMBER = 3;
    private volatile java.lang.Object answer_;
    /**
     * <code>string answer = 3;</code>
     */
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        answer_ = s;
        return s;
      }
    }
    /**
     * <code>string answer = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getQuestionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, question_);
      }
      if (!getAnswerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, answer_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getQuestionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, question_);
      }
      if (!getAnswerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, answer_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion)) {
        return super.equals(obj);
      }
      fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion other = (fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getQuestion()
          .equals(other.getQuestion());
      result = result && getAnswer()
          .equals(other.getAnswer());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + QUESTION_FIELD_NUMBER;
      hash = (53 * hash) + getQuestion().hashCode();
      hash = (37 * hash) + ANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getAnswer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SurveyQuestion}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SurveyQuestion)
        fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.eip.aura.udp.proto.SurveyProto.internal_static_SurveyQuestion_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.eip.aura.udp.proto.SurveyProto.internal_static_SurveyQuestion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.class, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder.class);
      }

      // Construct using fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        question_ = "";

        answer_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.eip.aura.udp.proto.SurveyProto.internal_static_SurveyQuestion_descriptor;
      }

      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion getDefaultInstanceForType() {
        return fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.getDefaultInstance();
      }

      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion build() {
        fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion buildPartial() {
        fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion result = new fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion(this);
        result.id_ = id_;
        result.question_ = question_;
        result.answer_ = answer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion) {
          return mergeFrom((fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion other) {
        if (other == fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getQuestion().isEmpty()) {
          question_ = other.question_;
          onChanged();
        }
        if (!other.getAnswer().isEmpty()) {
          answer_ = other.answer_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object question_ = "";
      /**
       * <code>string question = 2;</code>
       */
      public java.lang.String getQuestion() {
        java.lang.Object ref = question_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          question_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string question = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQuestionBytes() {
        java.lang.Object ref = question_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          question_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string question = 2;</code>
       */
      public Builder setQuestion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        question_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string question = 2;</code>
       */
      public Builder clearQuestion() {
        
        question_ = getDefaultInstance().getQuestion();
        onChanged();
        return this;
      }
      /**
       * <code>string question = 2;</code>
       */
      public Builder setQuestionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        question_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answer_ = "";
      /**
       * <code>string answer = 3;</code>
       */
      public java.lang.String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          answer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string answer = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAnswerBytes() {
        java.lang.Object ref = answer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string answer = 3;</code>
       */
      public Builder setAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        answer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 3;</code>
       */
      public Builder clearAnswer() {
        
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 3;</code>
       */
      public Builder setAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        answer_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SurveyQuestion)
    }

    // @@protoc_insertion_point(class_scope:SurveyQuestion)
    private static final fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion();
    }

    public static fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SurveyQuestion>
        PARSER = new com.google.protobuf.AbstractParser<SurveyQuestion>() {
      public SurveyQuestion parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SurveyQuestion(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SurveyQuestion> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SurveyQuestion> getParserForType() {
      return PARSER;
    }

    public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SurveyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Survey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>int32 user_id = 3;</code>
     */
    int getUserId();

    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    java.util.List<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion> 
        getQuestionsList();
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion getQuestions(int index);
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    int getQuestionsCount();
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    java.util.List<? extends fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder> 
        getQuestionsOrBuilderList();
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder getQuestionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Survey}
   */
  public  static final class Survey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Survey)
      SurveyOrBuilder {
    // Use Survey.newBuilder() to construct.
    private Survey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Survey() {
      type_ = "";
      id_ = 0;
      userId_ = 0;
      questions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Survey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 24: {

              userId_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                questions_ = new java.util.ArrayList<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion>();
                mutable_bitField0_ |= 0x00000008;
              }
              questions_.add(
                  input.readMessage(fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          questions_ = java.util.Collections.unmodifiableList(questions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.eip.aura.udp.proto.SurveyProto.internal_static_Survey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.eip.aura.udp.proto.SurveyProto.internal_static_Survey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.eip.aura.udp.proto.SurveyProto.Survey.class, fr.eip.aura.udp.proto.SurveyProto.Survey.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USER_ID_FIELD_NUMBER = 3;
    private int userId_;
    /**
     * <code>int32 user_id = 3;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int QUESTIONS_FIELD_NUMBER = 4;
    private java.util.List<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion> questions_;
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    public java.util.List<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion> getQuestionsList() {
      return questions_;
    }
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    public java.util.List<? extends fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder> 
        getQuestionsOrBuilderList() {
      return questions_;
    }
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    public int getQuestionsCount() {
      return questions_.size();
    }
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion getQuestions(int index) {
      return questions_.get(index);
    }
    /**
     * <code>repeated .SurveyQuestion questions = 4;</code>
     */
    public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder getQuestionsOrBuilder(
        int index) {
      return questions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (userId_ != 0) {
        output.writeInt32(3, userId_);
      }
      for (int i = 0; i < questions_.size(); i++) {
        output.writeMessage(4, questions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userId_);
      }
      for (int i = 0; i < questions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, questions_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.eip.aura.udp.proto.SurveyProto.Survey)) {
        return super.equals(obj);
      }
      fr.eip.aura.udp.proto.SurveyProto.Survey other = (fr.eip.aura.udp.proto.SurveyProto.Survey) obj;

      boolean result = true;
      result = result && getType()
          .equals(other.getType());
      result = result && (getId()
          == other.getId());
      result = result && (getUserId()
          == other.getUserId());
      result = result && getQuestionsList()
          .equals(other.getQuestionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      if (getQuestionsCount() > 0) {
        hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getQuestionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.SurveyProto.Survey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.eip.aura.udp.proto.SurveyProto.Survey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Survey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Survey)
        fr.eip.aura.udp.proto.SurveyProto.SurveyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.eip.aura.udp.proto.SurveyProto.internal_static_Survey_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.eip.aura.udp.proto.SurveyProto.internal_static_Survey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.eip.aura.udp.proto.SurveyProto.Survey.class, fr.eip.aura.udp.proto.SurveyProto.Survey.Builder.class);
      }

      // Construct using fr.eip.aura.udp.proto.SurveyProto.Survey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQuestionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";

        id_ = 0;

        userId_ = 0;

        if (questionsBuilder_ == null) {
          questions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          questionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.eip.aura.udp.proto.SurveyProto.internal_static_Survey_descriptor;
      }

      public fr.eip.aura.udp.proto.SurveyProto.Survey getDefaultInstanceForType() {
        return fr.eip.aura.udp.proto.SurveyProto.Survey.getDefaultInstance();
      }

      public fr.eip.aura.udp.proto.SurveyProto.Survey build() {
        fr.eip.aura.udp.proto.SurveyProto.Survey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.eip.aura.udp.proto.SurveyProto.Survey buildPartial() {
        fr.eip.aura.udp.proto.SurveyProto.Survey result = new fr.eip.aura.udp.proto.SurveyProto.Survey(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.id_ = id_;
        result.userId_ = userId_;
        if (questionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            questions_ = java.util.Collections.unmodifiableList(questions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.questions_ = questions_;
        } else {
          result.questions_ = questionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.eip.aura.udp.proto.SurveyProto.Survey) {
          return mergeFrom((fr.eip.aura.udp.proto.SurveyProto.Survey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.eip.aura.udp.proto.SurveyProto.Survey other) {
        if (other == fr.eip.aura.udp.proto.SurveyProto.Survey.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (questionsBuilder_ == null) {
          if (!other.questions_.isEmpty()) {
            if (questions_.isEmpty()) {
              questions_ = other.questions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureQuestionsIsMutable();
              questions_.addAll(other.questions_);
            }
            onChanged();
          }
        } else {
          if (!other.questions_.isEmpty()) {
            if (questionsBuilder_.isEmpty()) {
              questionsBuilder_.dispose();
              questionsBuilder_ = null;
              questions_ = other.questions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              questionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQuestionsFieldBuilder() : null;
            } else {
              questionsBuilder_.addAllMessages(other.questions_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.eip.aura.udp.proto.SurveyProto.Survey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.eip.aura.udp.proto.SurveyProto.Survey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 3;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 3;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 3;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion> questions_ =
        java.util.Collections.emptyList();
      private void ensureQuestionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          questions_ = new java.util.ArrayList<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion>(questions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder> questionsBuilder_;

      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public java.util.List<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion> getQuestionsList() {
        if (questionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(questions_);
        } else {
          return questionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public int getQuestionsCount() {
        if (questionsBuilder_ == null) {
          return questions_.size();
        } else {
          return questionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion getQuestions(int index) {
        if (questionsBuilder_ == null) {
          return questions_.get(index);
        } else {
          return questionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder setQuestions(
          int index, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion value) {
        if (questionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestionsIsMutable();
          questions_.set(index, value);
          onChanged();
        } else {
          questionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder setQuestions(
          int index, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder builderForValue) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.set(index, builderForValue.build());
          onChanged();
        } else {
          questionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder addQuestions(fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion value) {
        if (questionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestionsIsMutable();
          questions_.add(value);
          onChanged();
        } else {
          questionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder addQuestions(
          int index, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion value) {
        if (questionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestionsIsMutable();
          questions_.add(index, value);
          onChanged();
        } else {
          questionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder addQuestions(
          fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder builderForValue) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.add(builderForValue.build());
          onChanged();
        } else {
          questionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder addQuestions(
          int index, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder builderForValue) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.add(index, builderForValue.build());
          onChanged();
        } else {
          questionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder addAllQuestions(
          java.lang.Iterable<? extends fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion> values) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, questions_);
          onChanged();
        } else {
          questionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder clearQuestions() {
        if (questionsBuilder_ == null) {
          questions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          questionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public Builder removeQuestions(int index) {
        if (questionsBuilder_ == null) {
          ensureQuestionsIsMutable();
          questions_.remove(index);
          onChanged();
        } else {
          questionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder getQuestionsBuilder(
          int index) {
        return getQuestionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder getQuestionsOrBuilder(
          int index) {
        if (questionsBuilder_ == null) {
          return questions_.get(index);  } else {
          return questionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public java.util.List<? extends fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder> 
           getQuestionsOrBuilderList() {
        if (questionsBuilder_ != null) {
          return questionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(questions_);
        }
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder addQuestionsBuilder() {
        return getQuestionsFieldBuilder().addBuilder(
            fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.getDefaultInstance());
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder addQuestionsBuilder(
          int index) {
        return getQuestionsFieldBuilder().addBuilder(
            index, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.getDefaultInstance());
      }
      /**
       * <code>repeated .SurveyQuestion questions = 4;</code>
       */
      public java.util.List<fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder> 
           getQuestionsBuilderList() {
        return getQuestionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder> 
          getQuestionsFieldBuilder() {
        if (questionsBuilder_ == null) {
          questionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestion.Builder, fr.eip.aura.udp.proto.SurveyProto.SurveyQuestionOrBuilder>(
                  questions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          questions_ = null;
        }
        return questionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Survey)
    }

    // @@protoc_insertion_point(class_scope:Survey)
    private static final fr.eip.aura.udp.proto.SurveyProto.Survey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.eip.aura.udp.proto.SurveyProto.Survey();
    }

    public static fr.eip.aura.udp.proto.SurveyProto.Survey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Survey>
        PARSER = new com.google.protobuf.AbstractParser<Survey>() {
      public Survey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Survey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Survey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Survey> getParserForType() {
      return PARSER;
    }

    public fr.eip.aura.udp.proto.SurveyProto.Survey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SurveyQuestion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SurveyQuestion_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Survey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Survey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014survey.proto\">\n\016SurveyQuestion\022\n\n\002id\030\001" +
      " \001(\005\022\020\n\010question\030\002 \001(\t\022\016\n\006answer\030\003 \001(\t\"W" +
      "\n\006Survey\022\014\n\004type\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\017\n\007us" +
      "er_id\030\003 \001(\005\022\"\n\tquestions\030\004 \003(\0132\017.SurveyQ" +
      "uestionB$\n\025fr.eip.aura.udp.protoB\013Survey" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SurveyQuestion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SurveyQuestion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SurveyQuestion_descriptor,
        new java.lang.String[] { "Id", "Question", "Answer", });
    internal_static_Survey_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Survey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Survey_descriptor,
        new java.lang.String[] { "Type", "Id", "UserId", "Questions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
