// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package fr.eip.aura.udp.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>int32 doctor_id = 3;</code>
     */
    int getDoctorId();

    /**
     * <code>string firstname = 4;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>string firstname = 4;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    /**
     * <code>string lastname = 5;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>string lastname = 5;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>string gender = 6;</code>
     */
    java.lang.String getGender();
    /**
     * <code>string gender = 6;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>string birthday_date = 7;</code>
     */
    java.lang.String getBirthdayDate();
    /**
     * <code>string birthday_date = 7;</code>
     */
    com.google.protobuf.ByteString
        getBirthdayDateBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      type_ = "";
      id_ = 0;
      doctorId_ = 0;
      firstname_ = "";
      lastname_ = "";
      gender_ = "";
      birthdayDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 24: {

              doctorId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              firstname_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              lastname_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              birthdayDate_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.eip.aura.udp.proto.UserProto.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.eip.aura.udp.proto.UserProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.eip.aura.udp.proto.UserProto.User.class, fr.eip.aura.udp.proto.UserProto.User.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DOCTOR_ID_FIELD_NUMBER = 3;
    private int doctorId_;
    /**
     * <code>int32 doctor_id = 3;</code>
     */
    public int getDoctorId() {
      return doctorId_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object firstname_;
    /**
     * <code>string firstname = 4;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstname_ = s;
        return s;
      }
    }
    /**
     * <code>string firstname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object lastname_;
    /**
     * <code>string lastname = 5;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastname_ = s;
        return s;
      }
    }
    /**
     * <code>string lastname = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 6;
    private volatile java.lang.Object gender_;
    /**
     * <code>string gender = 6;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>string gender = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_DATE_FIELD_NUMBER = 7;
    private volatile java.lang.Object birthdayDate_;
    /**
     * <code>string birthday_date = 7;</code>
     */
    public java.lang.String getBirthdayDate() {
      java.lang.Object ref = birthdayDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthdayDate_ = s;
        return s;
      }
    }
    /**
     * <code>string birthday_date = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBirthdayDateBytes() {
      java.lang.Object ref = birthdayDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthdayDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (doctorId_ != 0) {
        output.writeInt32(3, doctorId_);
      }
      if (!getFirstnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, firstname_);
      }
      if (!getLastnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lastname_);
      }
      if (!getGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gender_);
      }
      if (!getBirthdayDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, birthdayDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (doctorId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, doctorId_);
      }
      if (!getFirstnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, firstname_);
      }
      if (!getLastnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lastname_);
      }
      if (!getGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gender_);
      }
      if (!getBirthdayDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, birthdayDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fr.eip.aura.udp.proto.UserProto.User)) {
        return super.equals(obj);
      }
      fr.eip.aura.udp.proto.UserProto.User other = (fr.eip.aura.udp.proto.UserProto.User) obj;

      boolean result = true;
      result = result && getType()
          .equals(other.getType());
      result = result && (getId()
          == other.getId());
      result = result && (getDoctorId()
          == other.getDoctorId());
      result = result && getFirstname()
          .equals(other.getFirstname());
      result = result && getLastname()
          .equals(other.getLastname());
      result = result && getGender()
          .equals(other.getGender());
      result = result && getBirthdayDate()
          .equals(other.getBirthdayDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DOCTOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDoctorId();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstname().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastname().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + BIRTHDAY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdayDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fr.eip.aura.udp.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fr.eip.aura.udp.proto.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        fr.eip.aura.udp.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.eip.aura.udp.proto.UserProto.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.eip.aura.udp.proto.UserProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.eip.aura.udp.proto.UserProto.User.class, fr.eip.aura.udp.proto.UserProto.User.Builder.class);
      }

      // Construct using fr.eip.aura.udp.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";

        id_ = 0;

        doctorId_ = 0;

        firstname_ = "";

        lastname_ = "";

        gender_ = "";

        birthdayDate_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.eip.aura.udp.proto.UserProto.internal_static_User_descriptor;
      }

      public fr.eip.aura.udp.proto.UserProto.User getDefaultInstanceForType() {
        return fr.eip.aura.udp.proto.UserProto.User.getDefaultInstance();
      }

      public fr.eip.aura.udp.proto.UserProto.User build() {
        fr.eip.aura.udp.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.eip.aura.udp.proto.UserProto.User buildPartial() {
        fr.eip.aura.udp.proto.UserProto.User result = new fr.eip.aura.udp.proto.UserProto.User(this);
        result.type_ = type_;
        result.id_ = id_;
        result.doctorId_ = doctorId_;
        result.firstname_ = firstname_;
        result.lastname_ = lastname_;
        result.gender_ = gender_;
        result.birthdayDate_ = birthdayDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.eip.aura.udp.proto.UserProto.User) {
          return mergeFrom((fr.eip.aura.udp.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.eip.aura.udp.proto.UserProto.User other) {
        if (other == fr.eip.aura.udp.proto.UserProto.User.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getDoctorId() != 0) {
          setDoctorId(other.getDoctorId());
        }
        if (!other.getFirstname().isEmpty()) {
          firstname_ = other.firstname_;
          onChanged();
        }
        if (!other.getLastname().isEmpty()) {
          lastname_ = other.lastname_;
          onChanged();
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (!other.getBirthdayDate().isEmpty()) {
          birthdayDate_ = other.birthdayDate_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.eip.aura.udp.proto.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.eip.aura.udp.proto.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int doctorId_ ;
      /**
       * <code>int32 doctor_id = 3;</code>
       */
      public int getDoctorId() {
        return doctorId_;
      }
      /**
       * <code>int32 doctor_id = 3;</code>
       */
      public Builder setDoctorId(int value) {
        
        doctorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 doctor_id = 3;</code>
       */
      public Builder clearDoctorId() {
        
        doctorId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstname_ = "";
      /**
       * <code>string firstname = 4;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstname = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstname = 4;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstname = 4;</code>
       */
      public Builder clearFirstname() {
        
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>string firstname = 4;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>string lastname = 5;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastname = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastname = 5;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastname = 5;</code>
       */
      public Builder clearLastname() {
        
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>string lastname = 5;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <code>string gender = 6;</code>
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gender = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gender = 6;</code>
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 6;</code>
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 6;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birthdayDate_ = "";
      /**
       * <code>string birthday_date = 7;</code>
       */
      public java.lang.String getBirthdayDate() {
        java.lang.Object ref = birthdayDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthdayDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string birthday_date = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBirthdayDateBytes() {
        java.lang.Object ref = birthdayDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthdayDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthday_date = 7;</code>
       */
      public Builder setBirthdayDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthdayDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string birthday_date = 7;</code>
       */
      public Builder clearBirthdayDate() {
        
        birthdayDate_ = getDefaultInstance().getBirthdayDate();
        onChanged();
        return this;
      }
      /**
       * <code>string birthday_date = 7;</code>
       */
      public Builder setBirthdayDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthdayDate_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final fr.eip.aura.udp.proto.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fr.eip.aura.udp.proto.UserProto.User();
    }

    public static fr.eip.aura.udp.proto.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public fr.eip.aura.udp.proto.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"\177\n\004User\022\014\n\004type\030\001 \001(\t\022\n\n\002id" +
      "\030\002 \001(\005\022\021\n\tdoctor_id\030\003 \001(\005\022\021\n\tfirstname\030\004" +
      " \001(\t\022\020\n\010lastname\030\005 \001(\t\022\016\n\006gender\030\006 \001(\t\022\025" +
      "\n\rbirthday_date\030\007 \001(\tB\"\n\025fr.eip.aura.udp" +
      ".protoB\tUserProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Type", "Id", "DoctorId", "Firstname", "Lastname", "Gender", "BirthdayDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
